### ISSUE TITLE
Index Error on 

### ISSUE THREAD

**Issue by sousasag** [rabrahm/ceres#11]
I got this error: IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

function def b_col(d):

	for i in range(len(ps)):
		d2[ps[i][0]:ps[i][1],ps[i][2]] = 1

I fixed locally with adding the following line before the for:
	ps = np.array(ps).astype(int)

**Comment by sbrems** [comment]
Hello,
I get the same error. I think there was a change at some python2.x < python 2.7 version where it is not allowed to use floats for indexing anymore. So after updating python 2 everyone should get this error.
However, I get a similar error from /utils/Correlation/correlation.py in l.625: rot = vsini[AI]
I think you need to add int() in the line before:
AI = int(numpy.where(difs == numpy.min(difs))[0])

**Comment by psarkis** [comment]
I also had the error as @sousasag : IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices
Fixed it as mentioned suggested.

Then I also had the same error as @sbrems , fixed it by typing the following:
AI = int(numpy.where(difs == numpy.min(difs))[0])

**Comment by rabrahm** [comment]
Thanks for pointing this out. Both bugs have been fixed.
