### ISSUE TITLE
Error on import Marsh

### ISSUE THREAD

**Issue by bmorris3** [rabrahm/ceres#17]
Hi! I'm looking to use ceres on HIRES spectra, and hit upon this error: 

```
Traceback (most recent call last):
  File "hirespipe.py", line 20, in <module>
    import hiresutils
  File "/Users/bmmorris/git/ceres/hires/hiresutils.py", line 11, in <module>
    import GLOBALutils
  File "../utils/GLOBALutils/GLOBALutils.py", line 19, in <module>
    import Marsh
ImportError: No module named Marsh
```

Any tips? 
Thanks!

**Comment by rabrahm** [comment]
Marsh is the C code that does the optimal extraction. It should have been compiled when you installed CERES with:

    python install.py

You can try to compile it directly with:

    cd utils/OptExtract
    python setup.py build
    mv build/lib.your.system.props/Marsh.so .

**Comment by bmorris3** [comment]
Perfect thanks!
