### ISSUE TITLE
initial wavelength calibration for feros pipeline

### ISSUE THREAD

**Issue by awmann** [rabrahm/ceres#28]
First off, thanks for providing this pipeline publicly. 

I'm running into an issue with the feros pipeline. The extraction looks fine on inspection, but I hit an error with the initial wavelength calibration:

	Wavelength solution of ThAr calibration spectra:
		Computing wavelength solution of ThAr file /Users/andrewmann/feros/FEROS.2004-06-04T22:08:11.593.fits
Traceback (most recent call last):
  File "ferospipe.py", line 427, in <module>
    Dump_AllLines=True, Cheby=use_cheby,porder=ncoef_x,del_width=4.0)
  File "/Users/andrewmann/ceres/utils/GLOBALutils/GLOBALutils.py", line 1897, in Initial_Wav_Calibration
    f = open(filename).readlines()
IOError: [Errno 2] No such file or directory: '/Users/andrewmann/ceres/feros/wavcals/order_09.harps.3iwdat'

This error is consistent across older and much more recent data, setups, etc. I'm assuming the reason it is looking for a 'order_XX.harps.3iwdat' file while running FEROS data is that it uses HARPS for some sort of guess on the solution? Either way, the pipeline never tries to create this file (at least as far as I can tell), so I assume I should have had it already (and presumably for the other orders). I didn't see an obvious way around this step.

Can you provide some guidance here? At least what the file is supposed to look like?

Thanks,
Andrew

**Comment by rabrahm** [comment]
Hi Andrew, yes those are the reference wavelength calibration files, and they are part of the repository. Please check if you have those in ceres/feros/wavcals/. If not, you can download them from here: https://github.com/rabrahm/ceres/tree/master/feros/wavcals
Try also running ferospipe_fp.py instead of ferospipe.py.

**Comment by awmann** [comment]
Thanks! 
No idea why none of the wavecal folders got downloaded, but that's on my end.
