### ISSUE TITLE
Malloc error/seg fault in GLOBALutils.PCoeff

### ISSUE THREAD

**Issue by jmccormac01** [rabrahm/ceres#5]
Hi,
Apologies for the stream of issues recently. This is just a heads up. I have 9 nights of CAFE data and 7 of them run fine. Two of the night's reductions fail around the extraction of the orders in the object fibre. I put a `print(i)` in the lines below, to see where the problem is. I get the error message below. 

``` python
235     print "\t\tWill extract",nord,"orders for object fibre..."                                                                                                                        
236     for i in range(nord):                                                                                                                                                             
237         P_marsh = GLOBALutils.PCoeff( fl, c_all[i,:], ext_aperture, RO_fl, GA_fl,\                                                                                                    
238             NSigma_Marsh, S_Marsh, N_Marsh, Marsh_alg, min_extract_col,max_extract_col )                                                                                        
239         P    += P_marsh                                                                                                                                                               
240         print(i) 
```

```
        Tracing echelle orders...
                90 orders found.

        Extraction of Flat calibration frames:
                No extracted flat object spectra found or extraction forced, extracting and saving...
                Will extract 90 orders for object fibre...
0
1
2
... (skipped for obvious reasons)
87
88
python(48520,0x7fff7717f000) malloc: *** error for object 0x145ff6208: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    48520 abort      python cafepipe.py /Users/James/Dropbox/CAFE-OBS/data/160910_CAFE
```

It seems that the first 89 orders seem ok but the last one dies. On a different night's data I get a segmentation fault on the same order:

```
        Tracing echelle orders...
                90 orders found.

        Extraction of Flat calibration frames:
                No extracted flat object spectra found or extraction forced, extracting and saving...
                Will extract 90 orders for object fibre...
0
1
2
... (skipped for obvious reasons)
87
88
[1]    49833 segmentation fault  python cafepipe.py /Users/James/Dropbox/CAFE-OBS/data/160909_CAFE
```

Maybe these orders are too faint for optimal extraction. To test this I tweaked `nord=90` to `nord=89` and the problem went away. 

``` python
186     nord=89                                                                                                                                                                           
187     c_all = c_all[:nord]                                                                                                                                                              
188     print '\t\t'+ str(nord)+' orders found.' 
```

I plan to add a command line argument to `cafepipe.py` to allow manual selection of the orders.  

I thought I'd let you know as the underlying error causing the segfault/malloc errors (if they are not the same) are not handled. I can give you some data to test this with if you like. I've not looked at the Marsh.c code in depth.

**Comment by rabrahm** [comment]
Hi James. I don't think that this error is related to low SNR in the last order. It wold be great if you can send me the data to investigate the source of the error.

**Comment by jmccormac01** [comment]
Sure no problem. I can give you access to the data now.

**Comment by rabrahm** [comment]
Hi James, the problem was that the trace of the last order found was actually out of the CCD at the edges (due to the curvature of echelle orders). Now the pipeline checks for this and removes the orders that go out of the CCD. Please check if this change works for all your nights. In addition, the spectral classification module should work now if you download the models that are specified now at the end of the README.

**Comment by jmccormac01** [comment]
Hi Rafael, Great thanks. I've been following the pull request and issues/emails today. Thanks for checking this out. I'll grab the most recent version of CERES tomorrow. 

I have  another question. Maybe it is better we chat via email. I was wondering how much work is involved in setting up CERES for a new echelle spectrograph? We use the [FIES spectrograph](http://www.not.iac.es/instruments/fies/) a lot and CERES seems like an excellent solution for that also.

**Comment by rabrahm** [comment]
Hi James, It should be relatively straightforward I think. If you have some FIES data please send it to me. The most tedious part is the initial identification of the ThAr lines, so if you already have a reference wavelength solution it would help a lot.

**Comment by jmccormac01** [comment]
Hi Rafael, I'm closing this as you have fixed the issue. I will send you some FIES data shortly. Cheers. James
